spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jackson:
    time-zone: Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  default-flat-param-object: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, prometheus

token:
  secret: Q2VwQ2h6b1d6b1p6b1F6b1R6b1V6b1d6b1p6b1F6b1R6b1U=

api:
  v1: /api/v1
